language: objective-c
xcode_project: Tor.xcodeproj
addons:
homebrew:
  packages:
  - automake
  - autoconf
  - libtool
  - gettext
script:
  - xcodebuild $XCODE_ACTION -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "$XCODE_DESTINATION"
matrix:
  include:
    - xcode_scheme: "Tor-iOS"
      xcode_sdk: iphoneos
      osx_image: xcode11.3
      env:
        - XCODE_ACTION=build
        - XCODE_DESTINATION="generic/platform=iOS"
    - xcode_scheme: "Tor-iOS"
      xcode_sdk: iphonesimulator
      osx_image: xcode11.3
      env:
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 11 Pro"
    - xcode_scheme: "Tor-Mac"
      xcode_sdk: macosx
      osx_image: xcode11.3
      env:
        - XCODE_ACTION=build
        - XCODE_DESTINATION="arch=x86_64"
